#!/bin/sh
#
#   Startup/shutdown script for the ILS sip services in invenio
#
#   Linux chkconfig stuff:
#
#   chkconfig: 345 80 20
#   description: Startup/shutdown script for the SIP service
#
### BEGIN INIT INFO
# Provides: ils_sip
# Required-Start: $syslog $local_fs
# Required-Stop: $syslog $local_fs
# Should-Start: portreserve
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
# Short-Description: SIP server for Invenio ILS
# Description: The SIP server for Invenio ILS
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

prog=SIPserver

start () {
	echo -n $"Starting $prog: "
	cd /opt/SIPserver
	daemon --user apache "./sip_run.sh"
}

stop () {
	echo -n $"Starting $prog: "
	cd /opt/SIPserver
	daemon --user apache "./sip_shutdown.sh"
}

restart() {
	stop
	start
}

case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		restart
	;;
	*)

	echo $"Usage: $prog {start|stop|restart}" 
	exit 2
esac

exit $RETVAL
